export const BACKEND_ENDPOINTS = {
  createUser: { method: 'post', url: 'register' },
  authorizeUser: { method: 'post', url: 'login' },
  getUserByToken: { method: 'get', url: 'user' },
  deauthorizeUser: { method: 'post', url: 'logout' },
  addTheater: { method: 'post', url: 'theaters' },
  getTheater: { method: 'get', url: 'theater?id={theaterId}' },
  getTheaters: { method: 'get', url: 'theaters' },
  deleteTheater: { method: 'delete', url: 'theaters/{theaterId}' },
  uploadTheaterPhoto: { method: 'post', url: 'file/theater/photo' },
  updateTheater: { method: 'patch', url: 'theater?id={theaterId}' },
  addSpectacle: { method: 'post', url: 'spectacle' },
  getSpectacle: { method: 'get', url: 'spectacle?id={spectacleId}' },
  getSpectacles: { method: 'get', url: 'spectacles?theater_id={theaterId}' },
  deleteSpectacle: { method: 'delete', url: 'spectacles/{spectacleId}' },
  uploadSpectaclePoster: { method: 'post', url: 'file/spectacle/poster' },
  uploadSpectacleFirstExtraPhoto: { method: 'post', url: 'file/spectacle/preview' },
  uploadSpectacleSecondExtraPhoto: { method: 'post', url: 'file/spectacle/slider-poster' },
  updateSpectacle: { method: 'patch', url: 'spectacle?id={spectacleId}' },
  addEvent: { method: 'post', url: 'events' },
  getEvent: { method: 'get', url: 'events/{eventId}' },
  getEvents: { method: 'get', url: 'events?from={dateRangeStart}&to={dateRangeEnd}&name={spectacleName}&theater_id={theaterId}' },
  deleteEvents: { method: 'delete', url: 'events/{eventId}' },
  getMainPagePremieres: { method: 'get', url: 'events?is_choosen_for_main_page=true' }
}
